# Numpy Array

# Change Python List to Numpy Array

In [4]:
import numpy as np
import pandas as pd

In [13]:
list1=[1,2,3]
np_array_vectors=np.array(list1)
np_array_vectors

array([1, 2, 3])

In [14]:
list2=[[1,2,3],[4,5,6],[7,8,9]]
np_array_matrices=np.array(list2)
np_array_matrices

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Generate Array Using Numpy

In [17]:
np_list=np.arange(0,11,2)
np_list

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones(2)

array([1., 1.])

In [21]:
np.ones((2,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.random.rand(5)

array([0.01180588, 0.02035586, 0.90930331, 0.89932245, 0.61636621])

In [26]:
np.random.randn(5)

array([-0.4574754 , -0.18804073,  1.51388907,  0.40665063, -1.82023135])

In [30]:
np.random.randn(2,5)

array([[-1.05629111, -0.27294509, -1.05886369,  0.79128121, -0.25500575],
       [-0.31652066,  0.43125468, -0.42570532,  2.21516043,  1.19522471]])

In [31]:
np.random.randint(0,100,10)

array([10, 69, 42, 89, 38, 21, 90,  8, 79, 57])

# ReShape an Array

In [13]:
arr=np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
arr2=np.random.randint(1,100,10)
arr2

array([39, 19, 96, 85, 73, 36, 77, 67, 48, 70])

In [16]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr2.max()


96

In [21]:
arr2.min()

19

In [23]:
arr2.argmax()


2

In [24]:
arr2.argmin()

1

In [26]:
arr2.shape

(10,)

In [30]:
arr3=arr2.reshape(2,5)

In [31]:
arr3.shape

(2, 5)

# Numpy Indexing and Selection

In [32]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[2]

3

In [34]:
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [35]:
arr[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [38]:
arr2=arr[0:6]
arr2

array([1, 2, 3, 4, 5, 6])

In [39]:
arr2[1:6]=100

In [40]:
arr2

array([  1, 100, 100, 100, 100, 100])

In [41]:
arr

array([  1, 100, 100, 100, 100, 100,   7,   8,   9,  10])

In [44]:
arr3=arr.copy()
arr3

array([  1, 100, 100, 100, 100, 100,   7,   8,   9,  10])

In [45]:
arr3[1:5]=30
arr3

array([  1,  30,  30,  30,  30, 100,   7,   8,   9,  10])

In [46]:
arr

array([  1, 100, 100, 100, 100, 100,   7,   8,   9,  10])

In [47]:
new_arr=np.arange(50).reshape(5,10)
new_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [49]:
new_arr[2:4,1:5]

array([[21, 22, 23, 24],
       [31, 32, 33, 34]])

In [50]:
arr_condition=np.arange(10)
arr_condition

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr_condition[arr_condition>5]

array([6, 7, 8, 9])

In [53]:
results=arr_condition>5
results

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [54]:
arr_condition[results]

array([6, 7, 8, 9])

# Numpy Operation